# Generated by Django 4.0.3 on 2022-04-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_rename_name_carbrand_car_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
